# Generated by Django 5.1.4 on 2025-01-11 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_alter_screenshots_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screenshots",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="screenshots",
                to="portfolio.project",
            ),
        ),
    ]
